spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library-manager-system
    username: root
    password: 1314527788qwe
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher





knife4j:
  enable: true

