spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library-manager-system
    username: root
    password: 1314527788qwe
    driver-class-name: com.mysql.cj.jdbc.Driver


page helper:
  helper-dialect: library-manager-system
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
